import org.gradle.api.tasks.Sync
import org.gradle.language.jvm.tasks.ProcessResources

plugins {
    kotlin("multiplatform")
}

fun registerBridgeGenerator(
    taskName: String,
    name: String,
    sourceRelativePath: String,
    installFunName: String,
): TaskProvider<Task> {
    val capitalizedName = name.replaceFirstChar { if (it.isLowerCase()) it.titlecase() else it.toString() }
    val sourceFile = layout.projectDirectory.file(sourceRelativePath)
    return tasks.register(taskName) {
        inputs.file(sourceFile)
        val outputDir = layout.buildDirectory.dir("generated/$name/kotlin")
        outputs.dir(outputDir)
        doLast {
            val source = sourceFile.asFile.readText()
            require(!source.contains("\"\"\"")) {
                "$sourceRelativePath must not contain a triple double-quote sequence"
            }
            require(!source.contains("$")) {
                "$sourceRelativePath must not contain a dollar sign (Kotlin raw string embedding)"
            }
            val body = "() => (function () {\n" +
                source +
                "\n})()"
            val outFile = outputDir.get().file("org/tiqian/web/${capitalizedName}Generated.kt").asFile
            outFile.parentFile.mkdirs()
            outFile.writeText(
                "// Generated by $taskName from $sourceRelativePath. Do not edit.\n" +
                    "package org.tiqian.web\n\n" +
                    "@JsFun(\"\"\"" + body + "\"\"\")\n" +
                    "internal external fun $installFunName()\n"
            )
        }
    }
}

val generateCustodyBridge = registerBridgeGenerator(
    taskName = "generateCustodyBridge",
    name = "custodyBridge",
    sourceRelativePath = "npm/core/engine/custody.js",
    installFunName = "installEmbeddedCustodyScript",
)

val generateEligibilityBridge = registerBridgeGenerator(
    taskName = "generateEligibilityBridge",
    name = "eligibilityBridge",
    sourceRelativePath = "npm/core/engine/eligibility.js",
    installFunName = "installEmbeddedEligibilityScript",
)

val generateProgressiveJobBridge = registerBridgeGenerator(
    taskName = "generateProgressiveJobBridge",
    name = "progressiveJob",
    sourceRelativePath = "npm/core/engine/progressive-job.js",
    installFunName = "installEmbeddedProgressiveJobScript",
)

val generateCopyBridge = registerBridgeGenerator(
    taskName = "generateCopyBridge",
    name = "copy",
    sourceRelativePath = "npm/core/utils/copy.js",
    installFunName = "installEmbeddedCopyScript",
)

val generateContentReconcileBridge = registerBridgeGenerator(
    taskName = "generateContentReconcileBridge",
    name = "contentReconcile",
    sourceRelativePath = "npm/core/engine/content-reconcile.js",
    installFunName = "installEmbeddedContentReconcileScript",
)

val generateResponsiveMeasureBridge = registerBridgeGenerator(
    taskName = "generateResponsiveMeasureBridge",
    name = "responsiveMeasure",
    sourceRelativePath = "npm/core/engine/responsive-measure.js",
    installFunName = "installEmbeddedResponsiveMeasureScript",
)

val generateMarkdownLoweringBridge = registerBridgeGenerator(
    taskName = "generateMarkdownLoweringBridge",
    name = "markdownLowering",
    sourceRelativePath = "npm/core/engine/markdown-lowering.js",
    installFunName = "installEmbeddedMarkdownLoweringScript",
)

// DemoPreparedDomVendor: the ADR 0039 demo page loads only the Kotlin bundle,
// so after the native renderer's retirement (ADR 0053 B8.3c) it must serve
// the npm prepared-DOM renderer itself. The five modules are copied with
// their relative layout intact so their ES imports keep resolving; the
// module self-installs the renderer bridge at import time.
val vendoredPreparedDomRoot = layout.buildDirectory.dir("generated/preparedDomVendor")

val vendorPreparedDom = tasks.register<Sync>("vendorPreparedDom") {
    into(vendoredPreparedDomRoot)
    from(layout.projectDirectory.file("npm/snapshot-schema.js"))
    from(layout.projectDirectory.dir("npm/core/sampler/snapshot")) {
        include(
            "prepared-dom.js",
            "snapshot-source.js",
            "prepared-dom-markup.js",
            "prepared-dom-evidence.js",
        )
        into("core/sampler/snapshot")
    }
}

kotlin {
    js {
        // These generated names are package internals. Keep them stable while
        // the repository and Gradle project paths move to the shorter layout.
        outputModuleName.set("Tiqian-tiqian-web")
        browser {
            commonWebpackConfig {
                outputFileName = "tiqian-web.js"
            }
        }
        useEsModules()
        binaries.executable()
    }
    sourceSets {
        jsMain {
            kotlin.srcDir(layout.buildDirectory.dir("generated/custodyBridge/kotlin"))
            kotlin.srcDir(layout.buildDirectory.dir("generated/eligibilityBridge/kotlin"))
            kotlin.srcDir(layout.buildDirectory.dir("generated/progressiveJob/kotlin"))
            kotlin.srcDir(layout.buildDirectory.dir("generated/copy/kotlin"))
            kotlin.srcDir(layout.buildDirectory.dir("generated/contentReconcile/kotlin"))
            kotlin.srcDir(layout.buildDirectory.dir("generated/responsiveMeasure/kotlin"))
            kotlin.srcDir(layout.buildDirectory.dir("generated/markdownLowering/kotlin"))
            resources.srcDir(vendoredPreparedDomRoot)
            dependencies {
                api(project(":engine"))
                implementation(project(":platforms:web:shaping"))
            }
        }
        jsTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

tasks.matching { it.name.startsWith("compileKotlinJs") }.configureEach {
    dependsOn(generateCustodyBridge)
    dependsOn(generateEligibilityBridge)
    dependsOn(generateProgressiveJobBridge)
    dependsOn(generateCopyBridge)
    dependsOn(generateContentReconcileBridge)
    dependsOn(generateResponsiveMeasureBridge)
    dependsOn(generateMarkdownLoweringBridge)
}

tasks.named<ProcessResources>("jsProcessResources") {
    dependsOn(vendorPreparedDom)
    from(layout.projectDirectory.file("npm/styles.css"))
}

tasks.register<Sync>("assembleNpmPackage") {
    group = "distribution"
    description = "Builds the @tiqian/prose ESM package runtime."
    dependsOn("jsBrowserProductionWebpack")
    from(layout.buildDirectory.dir("kotlin-webpack/js/productionExecutable")) {
        include("tiqian-web.js")
    }
    into(layout.projectDirectory.dir("npm/runtime"))
}
