import org.gradle.api.tasks.Sync
import org.gradle.language.jvm.tasks.ProcessResources

plugins {
    kotlin("multiplatform")
}

val custodySource = layout.projectDirectory.file("npm/core/engine/custody.js")

val generateCustodyBridge = tasks.register("generateCustodyBridge") {
    inputs.file(custodySource)
    val outputDir = layout.buildDirectory.dir("generated/custodyBridge/kotlin")
    outputs.dir(outputDir)
    doLast {
        val source = custodySource.asFile.readText()
        require(!source.contains("\"\"\"")) {
            "npm/core/engine/custody.js must not contain a triple double-quote sequence"
        }
        require(!source.contains("$")) {
            "npm/core/engine/custody.js must not contain a dollar sign (Kotlin raw string embedding)"
        }
        val body = "() => (function () { if (globalThis.__TiqianCustody) return;\n" +
            source +
            "\n})()"
        val outFile = outputDir.get().file("org/tiqian/web/CustodyBridgeGenerated.kt").asFile
        outFile.parentFile.mkdirs()
        outFile.writeText(
            "// Generated by generateCustodyBridge from npm/core/engine/custody.js. Do not edit.\n" +
                "package org.tiqian.web\n\n" +
                "@JsFun(\"\"\"" + body + "\"\"\")\n" +
                "internal external fun installEmbeddedCustodyScript()\n"
        )
    }
}

kotlin {
    js {
        // These generated names are package internals. Keep them stable while
        // the repository and Gradle project paths move to the shorter layout.
        outputModuleName.set("Tiqian-tiqian-web")
        browser {
            commonWebpackConfig {
                outputFileName = "tiqian-web.js"
            }
        }
        useEsModules()
        binaries.executable()
    }
    sourceSets {
        jsMain {
            kotlin.srcDir(layout.buildDirectory.dir("generated/custodyBridge/kotlin"))
            dependencies {
                api(project(":engine"))
                implementation(project(":platforms:web:shaping"))
            }
        }
        jsTest.dependencies {
            implementation(kotlin("test"))
        }
    }
}

tasks.matching { it.name.startsWith("compileKotlinJs") }.configureEach {
    dependsOn(generateCustodyBridge)
}

tasks.named<ProcessResources>("jsProcessResources") {
    from(layout.projectDirectory.file("npm/styles.css"))
}

tasks.register<Sync>("assembleNpmPackage") {
    group = "distribution"
    description = "Builds the @tiqian/prose ESM package runtime."
    dependsOn("jsBrowserProductionWebpack")
    from(layout.buildDirectory.dir("kotlin-webpack/js/productionExecutable")) {
        include("tiqian-web.js")
    }
    into(layout.projectDirectory.dir("npm/runtime"))
}
